# Generated by Django 2.2.7 on 2020-03-28 10:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_patient_has_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=254)),
                ('tel', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='lab_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=200)),
                ('o_email', models.CharField(max_length=254)),
                ('o_tel', models.CharField(max_length=100)),
                ('o_address', models.CharField(max_length=200)),
                ('p_name', models.CharField(max_length=100)),
                ('p_age', models.CharField(max_length=3)),
                ('p_phone', models.CharField(max_length=11)),
                ('test_1', models.CharField(max_length=100)),
                ('test1_desc', models.TextField(max_length=500)),
                ('test_2', models.CharField(max_length=100)),
                ('test2_desc', models.TextField(max_length=500)),
                ('test_3', models.CharField(max_length=100)),
                ('test3_desc', models.TextField(max_length=500)),
                ('test_4', models.CharField(max_length=100)),
                ('test4_desc', models.TextField(max_length=500)),
                ('test_5', models.CharField(max_length=100)),
                ('test5_desc', models.TextField(max_length=500)),
                ('submit_date', models.DateField(default=datetime.datetime(2020, 3, 28, 10, 17, 20, 108428, tzinfo=utc))),
                ('p_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
