# Generated by Django 2.2.7 on 2020-03-28 10:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_report',
            name='o_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.organization'),
        ),
        migrations.AlterField(
            model_name='lab_report',
            name='submit_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 28, 10, 55, 46, 69450, tzinfo=utc)),
        ),
    ]
