# Generated by Django 2.2.7 on 2020-03-29 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200328_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_report',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lab_report',
            name='submit_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 29, 9, 3, 24, 417277, tzinfo=utc)),
        ),
    ]
