# Generated by Django 2.2.7 on 2020-03-30 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200329_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_report',
            name='submit_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 30, 15, 47, 34, 401181, tzinfo=utc)),
        ),
    ]
