# Generated by Django 2.2.7 on 2020-03-30 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200330_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_report',
            name='submit_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 30, 15, 58, 16, 660407, tzinfo=utc)),
        ),
    ]
