# Generated by Django 2.2.7 on 2020-03-31 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200330_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_report',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 15, 23, 38, 712886, tzinfo=utc)),
        ),
    ]
