# Generated by Django 2.2.7 on 2020-04-11 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200331_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_report',
            name='preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lab_report',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 9, 50, 33, 688973, tzinfo=utc)),
        ),
    ]
