# Generated by Django 2.2.7 on 2020-04-11 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200411_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_report',
            name='preview',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lab_report',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 9, 51, 16, 9370, tzinfo=utc)),
        ),
    ]
