# Generated by Django 3.0.8 on 2020-07-23 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200411_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_report',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 18, 38, 56, 668096, tzinfo=utc)),
        ),
    ]
