# Generated by Django 2.2.7 on 2020-03-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemail', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=50)),
                ('dp', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('age', models.CharField(max_length=10)),
                ('p_identity', models.CharField(max_length=11)),
            ],
        ),
    ]
