# Generated by Django 2.2.7 on 2020-03-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200322_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dp',
            field=models.ImageField(default='default.jpg', upload_to='dp'),
        ),
    ]
