# Generated by Django 2.2.7 on 2020-03-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dp',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
